name: new_megatron
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.6.0
      - aniso8601==10.0.1
      - annotated-types==0.7.0
      - asciitree==0.3.3
      - blinker==1.9.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.0
      - coverage==7.8.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.3.0
      - fasteners==0.19
      - filelock==3.18.0
      - flask==3.1.1
      - flask-restful==0.3.10
      - fsspec==2025.3.2
      - gitdb==4.0.12
      - gitpython==3.1.44
      - huggingface-hub==0.31.2
      - idna==3.10
      - importlib-metadata==8.7.0
      - iniconfig==2.1.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - megatron-core==0.12.0
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numcodecs==0.13.1
      - numpy==2.2.5
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==12.575.51
      - nvidia-modelopt==0.29.0
      - nvidia-modelopt-core==0.29.0
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - packaging==25.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pluggy==1.5.0
      - protobuf==6.31.0
      - psutil==7.0.0
      - pulp==3.1.1
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pynvml==12.0.0
      - pytest==8.3.5
      - pytest-cov==6.1.1
      - pytest-mock==3.14.0
      - pytest-random-order==1.1.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==14.0.0
      - safetensors==0.5.3
      - scipy==1.15.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.28.0
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - tensorstore==0.1.75
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.7.0
      - torchprofile==0.0.4
      - torchvision==0.22.0
      - tqdm==4.67.1
      - transformer-engine==2.2.0
      - transformer-engine-cu12==2.2.0
      - transformer-engine-torch==2.2.0
      - transformers==4.51.3
      - triton==3.3.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.0
      - urllib3==2.4.0
      - wandb==0.19.11
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - zarr==2.18.3
      - zipp==3.21.0
prefix: /home/ec2-user/anaconda3/envs/new_megatron
